FROM nvidia/cuda:12.6.3-devel-ubuntu22.04

RUN apt update && apt install -y \
    git cmake build-essential libcurl4-openssl-dev curl \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/ggml-org/llama.cpp /llama.cpp

WORKDIR /
RUN cmake llama.cpp -B llama.cpp/build -DGGML_CUDA=ON -DBUILD_SHARED_LIBS=OFF \
    && cmake --build llama.cpp/build --clean-first --config Release -j8 --target llama-server

ENV PATH="/llama.cpp/build/bin:$PATH"
ENTRYPOINT ["llama-server"]
CMD [ \
    "--model", "/models/Qwen3.5-35B-A3B-UD-Q2_K_XL.gguf", \
    "--mmproj", "/models/mmproj-F16.gguf", \
    "--host", "0.0.0.0", \
    "--port", "8080", \
    "-ngl", "99", \
    "--temp", "0.6", \
    "--top-p", "0.95", \
    "--top-k", "20", \
    "--min-p", "0.00", \
    "--ctx-size", "32768", \
    "--alias", "local-model" \
]
