FROM python:3.11-slim

RUN pip install -q huggingface_hub hf_transfer

ENV HF_HUB_ENABLE_HF_TRANSFER=1


CMD ["python", "-c", \
"from huggingface_hub import hf_hub_download; \
hf_hub_download('unsloth/Qwen3.8-27B-GGUF', \
    'Qwen3.8-27B-UD-Q4_K_S.gguf', local_dir='/models'); \
hf_hub_download('ggml-org/Qwen3.8-27B-GGUF', \
    'mmproj-Qwen3.8-27B-Q8_0.gguf', local_dir='/models'); \
"]
