FROM pytorch/pytorch:2.10.0-cuda13.0-cudnn9-devel

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 https://github.com/comfyanonymous/ComfyUI /comfyui

WORKDIR /comfyui
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

RUN pip uninstall -y --break-system-packages kornia kornia_rs

EXPOSE 8188
CMD ["python", "main.py", "--listen", "0.0.0.0", "--port", "8188"]
